import { OnDestroy } from '@angular/core';
import { Context } from '@absmartly/javascript-sdk';
import { ABSmartlyConfig, ABSmartlyContextOptions } from './absmartly.types';
export declare class ABSmartlyService implements OnDestroy {
    private config;
    private sdk;
    private context;
    readonly ready: import("@angular/core").WritableSignal<boolean>;
    readonly failed: import("@angular/core").WritableSignal<boolean>;
    readonly loading: import("@angular/core").WritableSignal<boolean>;
    readonly error: import("@angular/core").WritableSignal<Error | null>;
    constructor(config: ABSmartlyConfig, existingContext: Context | null);
    private initializeState;
    treatment(experimentName: string): number;
    peek(experimentName: string): number;
    variableValue(key: string, defaultValue: string): string;
    peekVariableValue(key: string, defaultValue: string): string;
    variableKeys(): Record<string, unknown[]>;
    track(goalName: string, properties?: Record<string, unknown>): void;
    attribute(name: string, value: unknown): void;
    attributes(attrs: Record<string, unknown>): void;
    getAttribute(name: string): unknown;
    override(experimentName: string, variant: number): void;
    customAssignment(experimentName: string, variant: number): void;
    customFieldValue(experimentName: string, fieldName: string): unknown;
    customFieldKeys(): string[];
    customFieldValueType(experimentName: string, fieldName: string): string | null;
    setUnit(type: string, uid: string | number): void;
    getUnit(type: string): string | number;
    publish(): Promise<void>;
    finalize(): Promise<void>;
    refresh(): Promise<void>;
    resetContext(units: Record<string, string>, options?: ABSmartlyContextOptions): Promise<void>;
    isReady(): boolean;
    isFailed(): boolean;
    isFinalized(): boolean;
    pending(): number;
    experiments(): string[] | undefined;
    data(): unknown;
    getContext(): any;
    getSDK(): any;
    ngOnDestroy(): void;
}
